#!/usr/bin/python3.11
# -*- coding: utf-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
"""常量定义类"""


class Constant:
    MAGNIFYING_FOUR_POWER = 4
    SEED_CONTENT_MAX_LEN = 112
    SEED_CONTENT_MIN_LEN = 32
    PASSES_MAX_LEN = 64
    PASSES_MIN_LEN = 40
    PASSES_VALID_COUNT = 2
    IP_DEFAULT_PORT = 1024
    IP_MAX_PORT = 65535
    IP_ADDRESS = '127.0.0.1'
    TP_NUM_MIN = 1
    TP_NUM_MAX = 8
    MODEL_SEED_TYPE = 1
    DATA_SEED_TYPE = 2
    OBF_BY_ALL_SEED = 0
    OBF_BY_MODEL_SEED = 1
    OBF_BY_DATA_SEED = 2
    RESERVED_SPACE = 10 * 1024 * 1024
    FILE_MAX_LEN = 4096
    TSL_INFO_PARAM_SIZE = 6
    PSK_INFO_PARAM_SIZE = 3
    MAX_NPU_SIZE = 8
    QUERY_OBF_CLO_SIZE = 1536
    CA_CACHE_OBF_CLO_SIZE = 512
    OP_TYPE_INDEX = 0
    OP_DIM_INDEX = 1
    OP_CUSTOM_START_INDEX = 2
    OP_CUSTOM_LEN_INDEX = 3
    MODEL_CIPHERTEXT_FILE_NAME = "model_obf_ciphertext.txt"
    DATA_CIPHERTEXT_FILE_NAME = "data_obf_ciphertext.txt"
    OBF_COEFFICIENT_MIN = 0.01
    OBF_COEFFICIENT_MAX = 1.0
    SEED_ADD_IN = "seed_addin"
    MAX_DEVICE_ID = 15
    UNCONFUSED = "IDLE"
    MODEL_CONFUSED = "OBF_MODEL"
    DATA_CONFUSED = "OBF_DATA"
    BOTH_CONFUSED = "OBF_MODEL_AND_DATA"
    IMAGE_MAX_RATIO = 200
    MAX_BASE64_IMAGE_LENGTH = 26.7
    MAX_BYTES_IMAGE_LENGTH = 20
    MAX_BASE64_VIDEO_LENGTH = 681
    MAX_BYTES_VIDEO_LENGTH = 512
    VISION_DATA_LEN = 256
    MAX_THREADS = 32 