#!/usr/bin/env python3
"""
vLLM Agent Inference Adapter

Generated by agent-backend-adapter skill.
Fully standalone - no OpenCode dependencies.

Usage:
    python vllm_adapter_sample.py --model_path <model>
"""

import os
import argparse
import logging
from typing import List, Dict
from vllm import LLM, SamplingParams

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)


class AgentInferenceAdapter:
    """Standalone vLLM-based agent inference adapter."""
    
    def __init__(
        self,
        model_path: str,
        tensor_parallel_size: int = 1,
        gpu_memory_utilization: float = 0.8,
        max_model_len: int = 4096,
        dtype: str = "bfloat16",
        temperature: float = 0.7,
        max_tokens: int = 2048,
        top_p: float = 0.95
    ):
        self.model_path = model_path
        self.tensor_parallel_size = tensor_parallel_size
        
        self.llm = LLM(
            model=model_path,
            tensor_parallel_size=tensor_parallel_size,
            gpu_memory_utilization=gpu_memory_utilization,
            max_model_len=max_model_len,
            dtype=dtype,
            trust_remote_code=False,
            enforce_eager=False,
            enable_prefix_caching=True
        )
        
        self.sampling_params = SamplingParams(
            temperature=temperature,
            top_p=top_p,
            max_tokens=max_tokens
        )

    @staticmethod
    def _messages_to_prompt(messages: List[Dict[str, str]]) -> str:
        """Convert chat messages to prompt."""
        prompt = ""
        for msg in messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            prompt += f"{{role}}: {{content}}\n"
        return prompt

    def generate(self, prompts: List[str], **sampling_kwargs) -> List[str]:
        """Generate responses for a list of prompts."""
        params = self.sampling_params
        if sampling_kwargs:
            params = SamplingParams(**sampling_kwargs)
        
        outputs = self.llm.generate(prompts, params)
        return [o.outputs[0].text for o in outputs]
    
    def generate_chat(
        self,
        messages: List[Dict[str, str]],
        **sampling_kwargs
    ) -> str:
        """Generate response for chat messages."""
        prompt = AgentInferenceAdapter._messages_to_prompt(messages)
        return self.generate([prompt], **sampling_kwargs)[0]


def copy_file(src: str, dst: str):
    import shutil
    if os.path.exists(src):
        shutil.copy2(src, dst)
        logger.info(f"Copied: {src} -> {dst}")
    else:
        logger.warning(f"Source file not found: {src}")


def parse_args():
    parser = argparse.ArgumentParser(description="vLLM Adapter")
    parser.add_argument("--model_path", type=str, required=True)
    parser.add_argument("--tensor_parallel_size", type=int, default=1)
    parser.add_argument("--gpu_memory_utilization", type=float, default=0.8)
    parser.add_argument("--max_model_len", type=int, default=4096)
    parser.add_argument("--dtype", type=str, default="bfloat16")
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--max_tokens", type=int, default=2048)
    parser.add_argument("--prompt", type=str, default="Explain AI in one sentence.")
    parser.add_argument("--copy_from", type=str, default="",
                        help="Source file path to copy")
    parser.add_argument("--copy_to", type=str, default="",
                        help="Destination path for copied file")
    return parser.parse_args()


def main():
    args = parse_args()
    
    if args.copy_from and args.copy_to:
        copy_file(args.copy_from, args.copy_to)
        return
    
    adapter = AgentInferenceAdapter(
        model_path=args.model_path,
        tensor_parallel_size=args.tensor_parallel_size,
        gpu_memory_utilization=args.gpu_memory_utilization,
        max_model_len=args.max_model_len,
        dtype=args.dtype,
        temperature=args.temperature,
        max_tokens=args.max_tokens
    )
    
    logger.info("vLLM Adapter initialized")
    logger.info(f"Model: {args.model_path}")
    logger.info(f"Tensor Parallel: {args.tensor_parallel_size}")
    logger.info(f"Testing with prompt: {args.prompt}")
    
    results = adapter.generate([args.prompt])
    logger.info(f"Result: {results[0]}")


if __name__ == "__main__":
    main()
