#!/usr/bin/env python3
"""
VERL Agent Training Script

Generated by agent-backend-adapter skill.
Fully standalone - no OpenCode dependencies.

Usage:
    python verl_train_sample.py --model_path <model>
"""

import os
import argparse
import logging
import torch
import ray
from omegaconf import OmegaConf
from verl.trainer.ppo.ray_trainer import RayPPOTrainer

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def parse_args():
    parser = argparse.ArgumentParser(description="VERL Training")
    parser.add_argument("--model_path", type=str, required=True)
    parser.add_argument("--n_gpus", type=int, default=8)
    parser.add_argument("--algorithm", type=str, default="grpo")
    parser.add_argument("--n_samples", type=int, default=4)
    parser.add_argument("--learning_rate", type=float, default=1e-06)
    parser.add_argument("--total_epochs", type=int, default=15)
    parser.add_argument("--tensor_parallel_size", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./checkpoints")
    return parser.parse_args()


def main():
    args = parse_args()
    
    ray.init(
        num_cpus=args.n_gpus * 8,
        num_gpus=args.n_gpus,
        runtime_env={
            "env_vars": {
                "TOKENIZERS_PARALLELISM": "false",
                "NCCL_DEBUG": "WARN"
            }
        }
    )
    
    config = OmegaConf.create({
        "trainer": {
            "n_gpus_per_node": args.n_gpus,
            "nnodes": 1,
            "total_epochs": args.total_epochs,
            "save_freq": 100,
            "project_name": "agent_training",
            "experiment_name": "verl_grpo",
            "default_local_dir": args.output_dir
        },
        "actor_rollout_ref": {
            "model": {
                "path": args.model_path,
                "use_remove_padding": True
            },
            "actor": {
                "strategy": "fsdp2",
                "optim": {
                    "lr": args.learning_rate
                },
                "ppo_mini_batch_size": 256,
                "use_dynamic_bsz": True,
                "use_kl_loss": True,
                "kl_loss_coef": 0.001
            },
            "rollout": {
                "name": "vllm",
                "n": args.n_samples,
                "tensor_model_parallel_size": args.tensor_parallel_size,
                "gpu_memory_utilization": 0.8
            },
            "ref": {
                "strategy": "fsdp2"
            }
        },
        "algorithm": {
            "adv_estimator": args.algorithm,
            "gamma": 1.0,
            "lam": 0.95,
            "norm_adv_by_std_in_grpo": True,
            "kl_ctrl": {
                "kl_coef": 0.001
            }
        }
    })
    
    logger.info("VERL Training Configuration")
    logger.info(f"Model: {args.model_path}")
    logger.info(f"Algorithm: {args.algorithm}")
    logger.info(f"GPUs: {args.n_gpus}")
    logger.info("Configuration generated successfully!")


if __name__ == "__main__":
    main()
